### ISSUE TITLE
Whiteboard on Nextcloud 21 Error - Impossible to load Spacedeck whiteboard "cURL error 7: Failed connect to localhost:9666; Connection refused (see https:\/\/curl.haxx.se\/libcurl\/c\/libcurl-errors.html) for http:\/\/localhost:9666\/api\/spaces"

### ISSUE THREAD

**Issue by greavette** [nextcloud/integration_whiteboard#34] opened 2021-06-15 15:38 UTC
Whiteboard Version:  0.0.14
Nextcloud Version:  21.0.2

Error when trying to open a .whiteboard file in Nextcloud:

Impossible to load Spacedeck whiteboard "cURL error 7: Failed connect to localhost:9666; Connection refused (see https:\/\/curl.haxx.se\/libcurl\/c\/libcurl-errors.html) for http:\/\/localhost:9666\/api\/spaces"

This error is displayed in Nextcloud > Files and in Nextcloud > Logging when a .whiteboard file is attempting to open.

**Comment by TimmiORG** [comment] 2021-07-20 06:55
Hi,
I have the same also with Nextcloud 21.0.3.

**Comment by TimmiORG** [comment] 2021-07-29 20:05
Update: looks like this is an issue with SElinux. It is working if it is turned off.

**Comment by acsfer** [comment] 2021-12-06 14:47
Close as duplicate of https://github.com/nextcloud/integration_whiteboard/issues/36

**Closed by acsfer** 2021-12-06 14:47 UTC
