### ISSUE TITLE
Error while installing on NC21

### ISSUE THREAD

**Issue by szaimen** [nextcloud/integration_whiteboard#3] opened 2021-02-20 13:51 UTC
On NC21:
```
Error: Could not extract app integration_whiteboard: Out-of-path file extraction {/tmp/oc_tmp_9Fvh5B-folder/integration_whiteboard/data/spacedeck/node_modules/node-gyp/node_modules/.bin/semver --> ../semver/bin/semver}
```
```
{
  "reqId": "hMLAjEaEcO0j5VZ1IReR",
  "level": 3,
  "time": "2021-02-20T14:46:05+01:00",
  "user": "admin",
  "app": "settings",
  "method": "POST",
  "url": "/settings/apps/enable",
  "message": {
    "Exception": "Exception",
    "Message": "Could not extract app integration_whiteboard: Out-of-path file extraction {/tmp/oc_tmp_4xqQfw-folder/integration_whiteboard/data/spacedeck/node_modules/node-gyp/node_modules/.bin/semver --> ../semver/bin/semver}",
    "Code": 0,
    "Trace": [
      {
        "file": "/var/www/nextcloud/apps/settings/lib/Controller/AppSettingsController.php",
        "line": 445,
        "function": "downloadApp",
        "class": "OC\\Installer",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php",
        "line": 218,
        "function": "enableApps",
        "class": "OCA\\Settings\\Controller\\AppSettingsController",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php",
        "line": 127,
        "function": "executeController",
        "class": "OC\\AppFramework\\Http\\Dispatcher",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/lib/private/AppFramework/App.php",
        "line": 157,
        "function": "dispatch",
        "class": "OC\\AppFramework\\Http\\Dispatcher",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/lib/private/Route/Router.php",
        "line": 302,
        "function": "main",
        "class": "OC\\AppFramework\\App",
        "type": "::"
      },
      {
        "file": "/var/www/nextcloud/lib/base.php",
        "line": 993,
        "function": "match",
        "class": "OC\\Route\\Router",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/index.php",
        "line": 37,
        "function": "handleRequest",
        "class": "OC",
        "type": "::"
      }
    ],
    "File": "/var/www/nextcloud/lib/private/Installer.php",
    "Line": 328,
    "CustomMessage": "--"
  },
  "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.152 Safari/537.36",
  "version": "21.0.0.18",
  "id"
}
```

**Comment by szaimen** [comment] 2021-02-22 12:51
@eneiluj ?

**Comment by socialize-IT** [comment] 2021-02-22 22:28
Don't know what the problem is, but installing manually is working.

**Comment by szaimen** [comment] 2021-02-22 22:29
Yes, but installing manually is not really desirable.

**Comment by anoymouserver** [comment] 2021-02-23 07:34
Probably caused by a 3rd party dependency (see https://github.com/nextcloud/news/issues/1086#issuecomment-771914810 and https://github.com/nextcloud/3rdparty/issues/624) and will be fixed with https://github.com/nextcloud/3rdparty/pull/622

**Comment by eneiluj** [comment] 2021-02-23 10:10
Another solution to avoid this archive extraction issue is to remove all symlinks from the app. They are not used anyway.

v0.0.13 is out there. Could you confirm it works now?

**Comment by Pilzinsel64** [comment] 2021-02-23 11:27
I tried to update the manual installation of v0.0.12 to v0.0.13 right now using the app store and it worked!

**Comment by eneiluj** [comment] 2021-02-23 11:29
@Pilzinsel64 Thanks for the feedback! Let's wait for one or two other confirmations and close this issue.

**Comment by socialize-IT** [comment] 2021-02-23 11:31
Updating manually installed 0.0.12 to 0.0.13 via appstore worked for me too.

**Comment by abradshaw** [comment] 2021-02-23 11:33
I was having a problem installing 0.0.12 in my docker-compose version of NC 
version 0.0.13 just installed without errors  (now I need to find out where it is - can see the app)

**Comment by eneiluj** [comment] 2021-02-23 11:39
@socialize-IT Thanks for the feedback.

@abradshaw This app brings a new file type when pressing the "+" button in Files app. You can create `.whiteboard` files from there. Then you can share those files with other users, with public links or in Talk rooms.
I'm interested to know if the app works in a docker context.

**Comment by abradshaw** [comment] 2021-02-23 11:41
ah thanks @eneiluj - I can confirm its working fine now

**Comment by eneiluj** [comment] 2021-02-23 11:44
@abradshaw Thanks.

Let's close this then.

**Closed by eneiluj** 2021-02-23 11:44 UTC
Labels: bug
